Repository jain-rishabh-21/DoctorVerse, pull requests merged in 2023-06, with the labels that each got.

#79 feat(backend): added Doctor API and Token verification
  server/controller/doctor.js
  server/db/mongoose.js
  server/index.js
  server/model/doctor.js
  server/routes/doctor.js
  server/utlits/jwt.js
Labels: level2, gssoc23

#81 feat(frontend): adding routing with router-dom
  client/package.json
  client/src/App.js
  client/src/routes.js
Labels: level1, gssoc23

#99 docs(logo): added logo in readme file
  README.md
Labels: documentation, level1, gssoc23

#88 feat(authentication page): authentication page designed
  client/package-lock.json
  client/src/pages/Login/Login.js
  client/src/pages/Login/login.css
  client/src/routes.js
Labels: level3, gssoc23
